apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: todo-backend:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_CONN_STR
          value: mongodb://mongo.todo.svc.cluster.local:27017/todoapp
        - name: USE_DB_AUTH
          value: "false"
        - name: PORT
          value: "3500"
        ports:
        - containerPort: 3500
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: todo
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - name: http
    port: 3500
    targetPort: 3500
    nodePort: 30500